import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigator from "./components/layout/navigator/Navigator";
import Script from 'next/script'
import { AntdRegistry } from "@ant-design/nextjs-registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script src="/iconfont/iconfont.js" />
      <body className={inter.className}>
          <div className="main">
            <Navigator />

            <div>
              <AntdRegistry>
                  {children}
              </AntdRegistry>
            </div>
          </div>
      </body>
    </html>
  );
}
